### ISSUE TITLE
Check verify that we can render the CEF texture at 60 fps - hardware acceleration

### ISSUE THREAD

**Issue by kikohs** [vvvv/VL.CEF#10]
Hi,
I'm trying to test some dataviz library from VL but the framerate is not at 60 fps. WebGL is laggy as well.
In the following example, you can simply change any `data` value (on the left JSON) and the chart will update accordingly. (Activate dark mode on top redraws everything as well).
It's a good way to test whether the performance is enough to be displayed in Skia/Stride.

[cef_example.txt](https://github.com/vvvv/VL.CEF/files/8371023/cef_example.txt)
Thank you very much

**Comment by kikohs** [comment]
Great if the benchmark is the same. Maybe the shared texture flag should be on by default? 
Thanks for checking.

**Comment by azeno** [comment]
Newest build has shared texture enabled.
