### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by dorkykong** [vvvv/VL.CEF#11]
Hello,

I am trying to access this website https://experience.arcgis.com/experience/469740e70f96494e893379129516119a/page/%C3%9CBERSICHT/
through the webbrowser node but always get the error message mentoined in the title. I have found that this is a chromium bug that had been around a few years ago. 

Anyway to fix this?

**Comment by azeno** [comment]
Updating to a recent Chromium had been blocked in the past due to lack of hardware accelerated rendering. There was an ongoing issue in the CEF repo about it, will need to look it up and see. 

In the meantime you could download the official CEF browser example and see if it works with it.

**Comment by azeno** [comment]
Latest preview packages use a more recent Chromium version and open your posted address.
