### ISSUE TITLE
Does not respect autoplay in Youtube Embedded

### ISSUE THREAD

**Issue by seltzdesign** [vvvv/VL.CEF#12]
As noted here: https://discourse.vvvv.org/t/vl-cef-autoplay-youtube-video-not-working/21294/3, VL.CEF somehow blocks autoplay from working in Youtube embedded.

It works fine in other Chromium-based browsers like Brave.

Unless there is a very good technical reason, I believe it should respect autoplay and start playing an embedded video.

**Comment by seltzdesign** [comment]
Seems like there is a solution in this thread: https://bitbucket.org/chromiumembedded/cef/issues/2478/autoplay-policy-flag-not-respected (last comment)

**Comment by seltzdesign** [comment]
Note: autoplay does work with the flag mute=1 set in the URL. It would be great to be able to autoplay with sound, which would only be possible with the autoplay policy flag being set.

Thanks for considering this improvement and opening up more possibilities in VL.

**Comment by azeno** [comment]
Fixed in `VL.CEF.0.5.0-preview.3`
