### ISSUE TITLE
no mouse and red lines in WebRender (internal)

### ISSUE THREAD

**Issue by bluelemonade** [vvvv/VL.CEF#2]
I have red lines inside the WebRenderer(internal) in Version 2020.3.0-0043. (and 2020.2.2) From the Size Pin start a red line with the info Vector2 is no Vector2

**Comment by azeno** [comment]
I suspect you had a version mismatch. When using vvvv >= 2020.2 you'll need to install the preview versions of the package. For example 0.0.6-stride - see the readme at the front page.
