### ISSUE TITLE
Unable to build project with vvvv Gamma 2020.2.2

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.CEF#3]
I tried to build this project with gamma. It is possible to build it with  Gamma 2020.1.7 but the audio didn't playback on the target machines (Win10x64, doctors clinic). [VL.CEFBuildError-Gamma2020.2.2.txt](https://github.com/vvvv/VL.CEF/files/5529884/VL.CEFBuildError-Gamma2020.2.2.txt)

I've tried uninstalling Visual Studio 2017, installing VS2019, updating VS2019 and the VSBuildtools to the latest versions (not beta). I've also tried uninstalling and reinstalling vvvv 2020.2.2. I removed all the nugets from .nuget and app/local.vvvv/gamma/nuget/packages and removed the VL.CEF and other Nugets to force all packages to be built from new. Lastly I removed the source files from the gamma/export/src folder so all of these would need to be build from scratch when I try to export.

The key error seems to be this:
`Csc: : ERROR C:\Users\Igor\Documents\vvvv\gamma\Exports\src\VL.CEF.vl\VL.CEF.vl.cs(158,129): The type 'RendererBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Stride.Rendering, Version=4.0.0.1, Culture=neutral, PublicKeyToken=null'.`

This suggests that despite the option to have a Skia layer Stride is required for builds. I don't mind this, because Stride is now public, but it isn't stable and it isn't convenient for the team to be working on different versions of Gamma. It may also mean that this library, despite running on it, can't be compiled with Gamma 2020.2.2.

We would like to get to the bottom of what went wrong so we could use this library in the future.
[CEFTestFile.zip](https://github.com/vvvv/VL.CEF/files/5530149/CEFTestFile.zip)

**Comment by azeno** [comment]
I just pushed new packages (0.0.8-stride) which should fix those export issues. Note that to install them follow the updated instructions on https://github.com/vvvv/VL.CEF/blob/master/README.md - these special instructions shouldn't be necessary anymore once we get to a stable Stride release.

**Comment by YanYas** [comment]
Thanks for looking into this. The fix is successful.
