### ISSUE TITLE
Nuget package tries to install Stride and fails for most users

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.CEF#4]
when installing on a vvvv version that has a newer stride version, nuget tries to install stride vvvv-1307, this adds all packages to the nuget folder and will fail for users who don't have the vvvv nuget feed in their NuGet.config file.

from vvvv chat:

> alas trying to install the latest vl.cef (after installing Stride.Rendering -prerelease), I still get: Unable to find a version of 'Stride.Rendering' that is compatible with 'VL.CEF 0.0.8-stride constraint: Stride.Rendering (>= 4.0.0.1-vvvv-1307)'

**Comment by azeno** [comment]
Yes, see the special install instructions on the front page. For details see my answer in https://github.com/vvvv/VL.CEF/issues/3 as well as the corresponding commit. Short version, we need to get back to a stable Stride release. Once we have that, we won't need those special nuget sources anymore.

**Comment by azeno** [comment]
Well I keep the issue open for now as probably more people will run into this.
