### ISSUE TITLE
Current URL output pin

### ISSUE THREAD

**Issue by sebescudie** [vvvv/VL.CEF#6]
Hey,

Would it be possible to have an output pin that gives the current URL? Right now, if a user clicks a button or is redirected to a page, you don't know what URL they're visiting.

Use case is : I'd like to pop a web login form to login into a Spotify app I'm building. When the user successfully logs in, they're redirected to the app's landing page, and a `code` parameter is appended to the URL. This code has to be retrieved and added as a parameter to a second query that in turn gives the secret token needed by the lib to interact with a user's Spotify account.

Right now, I'm using a WebBrowser Form component that has a `Navigated` event that fires when a redirection/URL change happens.

Is there anything similar in CEF that could be ported to this plugin?

Thanks!

**Comment by azeno** [comment]
Omg, I didn't get any notifications from github about the issues posted here. Completely missed them. Will report back soon.

**Comment by azeno** [comment]
In >= 0.3.0 connect the `Url [WebBrowser]` node your `WebBrowser` to see the currently loaded URL.

**Comment by sebescudie** [comment]
Thanks, will have a look !
