### ISSUE TITLE
WebRenderer [Stride.Rendering] Keyboard input not working

### ISSUE THREAD

**Issue by davidbrrrr** [vvvv/VL.CEF#7]
Reproduce: open Helppatch "Overview Stride", load a page with an input field, start typing on keyboard.
Additionally. think about touchscreens and maybe add an option to call the onscreen keyboard?

**Comment by azeno** [comment]
Just pushed a new version (0.2.3) which should fix the text input not working at all. Regarding the onscreen keyboard some research would need to be done. I'm not exactly sure how that works. It's something the operating system provides, no?

**Comment by davidbrrrr** [comment]
confirmed. works now. regarding onscreen keyboard. I think its just osk.exe. Maybe the WebRenderer has an output with events that one can catch and do stuff like calling osk.exe on their own? Dont know.

**Comment by azeno** [comment]
Indeed there is an event for that which also says what keyboard should be opened. I will expose it as an observable.
